#!/bin/bash

export PYTHONPATH=/usr/local/lib/hahub

# echo "Starting HAWEB service..."
if [ ! -d /var/run/hahub ]
then
	echo "Creating /var/run/hahub directory..."
	mkdir /var/run/hahub
fi

if [ ! -d /var/log/hahub ]
then
	echo "Creating /var/log/hahub directory..."
	mkdir /var/log/hahub
fi

if [ -e /var/log/hahub/haweb-nohup.out ]
then
	# echo "Saving old haweb-nohup.out..."
	mv /var/log/hahub/haweb-nohup.out /var/log/hahub/haweb-nohup.out.old
fi

nohup /etc/hahub/hawebd.py > /var/log/hahub/haweb-nohup.out 2>&1 &

exit 0
