#!/bin/bash

echo "Starting HAHUB daemon..."
if [ ! -d /var/run/hahub ]
then
	echo "Creating /var/run/hahub directory..."
	mkdir /var/run/hahub
fi

if [ ! -d /var/log/hahub ]
then
	echo "Creating /var/log/hahub directory..."
	mkdir /var/log/hahub
fi

if [ -e /var/log/hahub/hahub.log ]
then
	echo "Saving old hahub.log..."
	mv /var/log/hahub/hahub.log /var/log/hahub/hahub.log.old
fi
echo > /var/log/hahub/hahub.log

if [ -e /var/log/hahub/nohup.out ]
then
	echo "Saving old nohup.out..."
	mv /var/log/hahub/nohup.out /var/log/hahub/nohup.out.old
fi

nohup /etc/hahub/hahubd.py > /var/log/hahub/nohup.out &

exit 0
