#!/bin/bash

STATUS=0
ps -p `cat /var/run/hahub/hahub.pid` > /dev/null
if [ $? -ne 0 ]; then
	echo "HAHUB process not found."
	STATUS=1
else
	kill -15 $(cat /var/run/hahub/hahub.pid) 2> /dev/null
	if [ $? -ne 0 ]; then
		echo "Failure stopping HAHUB"
		STATUS=1
	fi
fi

exit $STATUS
