#! /bin/bash
# /etc/init.d/hahub-svcs
#
### BEGIN INIT INFO
# Provides:          hahub haweb
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start hahub services
# Description:       Start hahub services HAHUB and HAWEB at boot time
### END INIT INFO

case "$1" in
	start)
		# echo "Starting service HAHUB"
		/etc/hahub/start-hahub
		# echo "Starting service HAWEB"
		/etc/hahub/start-haweb
		;;
	stop)
		# echo "Stopping service HAHUB"
		/etc/hahub/stop-hahub
		# echo "Stopping service HAWEB"
		/etc/hahub/stop-haweb
		;;
	status)
		ps -p `cat /var/run/hahub/hahub.pid`
		if [ $? -eq 0 ]; then
			echo "HaHubd running."
		fi
		ps -p `cat /var/run/hahub/haweb.pid`
		if [ $? -eq 0 ]; then
			echo "HaWebd running."
		fi
		;;
	*)
		echo "Usage: /etc/init.d/hahub-svcs {start|stop|status}"
		exit 1
		;;
esac

exit 0
